### ISSUE TITLE
request executable name change from cloc to cloc-rs (or something else entirely)

### ISSUE THREAD

**Issue by AlDanial** [ltoddy/cloc-rs#5]
Thanks for making me aware of your project with https://github.com/AlDanial/cloc/issues/518.  I wish you much success.

What strikes me as odd, however, is your choice to name your executable "cloc".  Perhaps you are unaware, but it is considered poor form to take the name of an existing program (https://github.com/AlDanial/cloc has been on github for five years, and at SourceForge for ten years before that).  I respectfully ask that you rename your executable to "cloc-rs" or perhaps come up with an entirely novel name.

**Comment by ltoddy** [comment]
Maybe you are right. @AlDanial

**Comment by Gaojianli** [comment]
@AlDanial renamed to `rcloc`

**Comment by AlDanial** [comment]
@Gaojianli : thanks
